
FAIL Fetch event handler throws after a successful respondWith() promise_test: Unhandled rejection with value: object "NotSupportedError: Passing MessagePort objects to postMessage is not yet supported"

