
FAIL PaymentRequestUpdateEvent constructor throws in a non-secure context assert_throws: function "() => {
    new PaymentRequestUpdateEvent("test");
  }" did not throw

